version: "3.9"  # optional since v1.27.0
services:
  db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    env_file:
      - .env
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
      - ./node_modules:/home/node/app/node_modules
    container_name: api
    expose:
      - '3000'
    ports:
      - '80:3000'
    depends_on:
      - db
      
    command: npm run dev